import { Inter } from "next/font/google";
import "./globals.css";
import { FlightProvider } from './components/client/FightContext';
import { AuthProvider } from './components/client/auth'
 
const inter = Inter({ subsets: ["latin"] });
 
export const metadata = {
  title: "Yatri-Tickets",
  description: "Generated by create next app",
};
 
export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <FlightProvider>
        {children}
        </FlightProvider>
        </AuthProvider>
      </body>
    </html>
  );
}